export interface Deal {
  name: string;
  slug: string;
  url: string;
  description: string;
  category: string;
  deal_type: "free_tier" | "limited_promotion" | "open_source" | "free_credits";
  deal_detail: string;
  free_until: string | null;
  value_usd_month: number;
  score: number;
  verified: boolean;
  source: string;
  tags: string[];
}

export const DEALS_SEED: Deal[] = [
  // === FREE CREDITS / FREE TIERS — LLM APIs ===
  {
    name: "Google Gemini API Free Tier",
    slug: "google-gemini-free",
    url: "https://ai.google.dev/gemini-api/docs/pricing",
    description: "Free access to Gemini 2.0 Flash, Gemini 1.5 Flash, and Gemini 1.5 Pro. 15 RPM, 1M tokens/day.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "Gemini 2.0 Flash: free, 15 RPM, 1M tokens/day. Gemini 1.5 Flash: free, 15 RPM, 1M tokens/day. Gemini 1.5 Pro: free, 2 RPM, 32K tokens/day.",
    free_until: null,
    value_usd_month: 50,
    score: 95,
    verified: true,
    source: "official",
    tags: ["llm", "api", "google", "gemini", "free-tier"],
  },
  {
    name: "Groq Free Tier",
    slug: "groq-free",
    url: "https://groq.com/pricing/",
    description: "Free API access to Llama 3.3 70B, Mixtral 8x7B, Gemma 2 9B. 30 RPM, 14,400 RPM daily limit.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "Llama 3.3 70B: free, 30 RPM. Mixtral 8x7B: free, 30 RPM. Gemma 2 9B: free, 30 RPM. No credit card required.",
    free_until: null,
    value_usd_month: 30,
    score: 92,
    verified: true,
    source: "official",
    tags: ["llm", "api", "groq", "inference", "free-tier"],
  },
  {
    name: "Cerebras Free Inference",
    slug: "cerebras-free",
    url: "https://www.cerebras.ai/inference",
    description: "Free API access to Llama 3.1 8B and 70B on Cerebras wafer-scale chips. Fastest inference available.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "Llama 3.1 8B: free, 30 RPM. Llama 3.1 70B: free, 30 RPM. 1000 tokens per request max.",
    free_until: null,
    value_usd_month: 25,
    score: 90,
    verified: true,
    source: "official",
    tags: ["llm", "api", "cerebras", "inference", "free-tier"],
  },
  {
    name: "Together AI Free Credits",
    slug: "together-free",
    url: "https://www.together.ai/pricing",
    description: "$1 free credits for new accounts. Access 200+ models including Llama, Mixtral, DeepSeek.",
    category: "LLM API",
    deal_type: "free_credits",
    deal_detail: "$1 free credits for new users. No expiration. Access to all models including Llama 3.1 405B, DeepSeek V3, Flux image gen.",
    free_until: null,
    value_usd_month: 1,
    score: 85,
    verified: true,
    source: "official",
    tags: ["llm", "api", "together", "credits", "free-credits"],
  },
  {
    name: "DeepInfra Free Tier",
    slug: "deepinfra-free",
    url: "https://deepinfra.com/pricing",
    description: "Free tier for Llama 3.1 8B and Mistral 7B. Pay-as-you-go for larger models.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "Llama 3.1 8B: free, 1 RPM. Mistral 7B: free, 1 RPM. Paid plans from $0.0001/token for larger models.",
    free_until: null,
    value_usd_month: 5,
    score: 75,
    verified: true,
    source: "official",
    tags: ["llm", "api", "deepinfra", "inference", "free-tier"],
  },
  {
    name: "Fireworks AI Free Tier",
    slug: "fireworks-free",
    url: "https://fireworks.ai/pricing",
    description: "Free tier for Llama 3.1 8B and Mixtral 8x7B. 1000 RPM, 1M tokens/day.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "Llama 3.1 8B: free, 1000 RPM. Mixtral 8x7B: free, 1000 RPM. 1M tokens/day limit.",
    free_until: null,
    value_usd_month: 20,
    score: 88,
    verified: true,
    source: "official",
    tags: ["llm", "api", "fireworks", "inference", "free-tier"],
  },
  {
    name: "OpenRouter Free Models",
    slug: "openrouter-free",
    url: "https://openrouter.ai/models?pricing=free",
    description: "100+ free models including Llama 3.1, Gemma 2, Mistral, Phi-3. No API key needed for some.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "100+ free models. Rate limited but unlimited usage. Includes Llama 3.1 8B/70B, Gemma 2 9B/27B, Mistral 7B, Phi-3 Mini.",
    free_until: null,
    value_usd_month: 40,
    score: 93,
    verified: true,
    source: "official",
    tags: ["llm", "api", "openrouter", "free-tier", "aggregator"],
  },
  {
    name: "Mistral AI Free Tier",
    slug: "mistral-free",
    url: "https://console.mistral.ai/",
    description: "Free tier for Mistral 7B, Mistral Small, and Codestral. 1 RPM for larger models.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "Mistral 7B: free, 30 RPM. Mistral Small: free, 1 RPM. Codestral: free, 1 RPM. No credit card required.",
    free_until: null,
    value_usd_month: 15,
    score: 82,
    verified: true,
    source: "official",
    tags: ["llm", "api", "mistral", "free-tier"],
  },
  {
    name: "Cloudflare Workers AI Free Tier",
    slug: "cloudflare-workers-ai-free",
    url: "https://developers.cloudflare.com/workers-ai/",
    description: "10,000 neurons/day free. Llama 3.1 8B, Mistral 7B, Stable Diffusion, Whisper.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "10,000 neurons/day free. Includes text generation, image generation, audio transcription. No credit card required.",
    free_until: null,
    value_usd_month: 10,
    score: 80,
    verified: true,
    source: "official",
    tags: ["llm", "api", "cloudflare", "free-tier", "edge"],
  },
  {
    name: "Hugging Face Inference API Free",
    slug: "huggingface-inference-free",
    url: "https://huggingface.co/inference-api",
    description: "Free inference for 100k+ models. Rate limited but unlimited usage.",
    category: "LLM API",
    deal_type: "free_tier",
    deal_detail: "Free tier: 1-2 RPM depending on model. Access to 100k+ models. No credit card required for free tier.",
    free_until: null,
    value_usd_month: 20,
    score: 85,
    verified: true,
    source: "official",
    tags: ["llm", "api", "huggingface", "free-tier"],
  },

  // === FREE TIERS — CODING TOOLS ===
  {
    name: "GitHub Copilot Free",
    slug: "github-copilot-free",
    url: "https://github.com/features/copilot",
    description: "2000 completions/month + 50 chat messages/month free. GPT-4o and Claude 3.5 Sonnet included.",
    category: "Code Assistant",
    deal_type: "free_tier",
    deal_detail: "2000 code completions/month. 50 chat messages/month. Access to GPT-4o, Claude 3.5 Sonnet, Gemini 1.5 Pro. VS Code + JetBrains.",
    free_until: null,
    value_usd_month: 19,
    score: 95,
    verified: true,
    source: "official",
    tags: ["coding", "copilot", "free-tier", "github", "ai"],
  },
  {
    name: "Cursor Free Tier",
    slug: "cursor-free",
    url: "https://www.cursor.com/",
    description: "2000 completions + 50 slow premium requests/month. VS Code fork with AI.",
    category: "Code Editor / AI",
    deal_type: "free_tier",
    deal_detail: "2000 code completions/month. 50 slow premium requests/month. Unlimited basic requests. GPT-4o, Claude 3.5 Sonnet.",
    free_until: null,
    value_usd_month: 20,
    score: 88,
    verified: true,
    source: "official",
    tags: ["coding", "editor", "cursor", "free-tier", "ai"],
  },
  {
    name: "Aider (Open Source)",
    slug: "aider",
    url: "https://aider.chat/",
    description: "Free AI pair coding in your terminal. Works with any LLM API. GPT-4, Claude, local models.",
    category: "Code Assistant",
    deal_type: "open_source",
    deal_detail: "100% free, open source. MIT license. Works with GPT-4, Claude, Gemini, DeepSeek, local models via Ollama.",
    free_until: null,
    value_usd_month: 0,
    score: 90,
    verified: true,
    source: "github",
    tags: ["coding", "ai", "terminal", "open-source", "pair-programming"],
  },
  {
    name: "Cline (Open Source)",
    slug: "cline",
    url: "https://cline.bot/",
    description: "Free autonomous coding agent for VS Code. Uses your own API key.",
    category: "Code Assistant",
    deal_type: "open_source",
    deal_detail: "100% free, open source. Apache 2.0. VS Code extension. Autonomous coding with any LLM API.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["coding", "ai", "vscode", "open-source", "agent"],
  },
  {
    name: "Roo Code (Open Source)",
    slug: "roo-code",
    url: "https://roocode.com/",
    description: "Free AI coding assistant for VS Code. Multi-model support, custom modes.",
    category: "Code Assistant",
    deal_type: "open_source",
    deal_detail: "100% free, open source. VS Code extension. Supports GPT-4, Claude, Gemini, local models. Custom coding modes.",
    free_until: null,
    value_usd_month: 0,
    score: 85,
    verified: true,
    source: "github",
    tags: ["coding", "ai", "vscode", "open-source"],
  },
  {
    name: "OpenCode (Open Source)",
    slug: "opencode",
    url: "https://opencode.ai/",
    description: "Free AI coding agent in your terminal. Supports multiple LLM providers.",
    category: "Code Assistant",
    deal_type: "open_source",
    deal_detail: "100% free, open source. Terminal-based. Supports OpenAI, Anthropic, Google, local models.",
    free_until: null,
    value_usd_month: 0,
    score: 82,
    verified: true,
    source: "github",
    tags: ["coding", "ai", "terminal", "open-source"],
  },

  // === FREE TIERS — PRODUCTIVITY ===
  {
    name: "Notion Free Plan",
    slug: "notion-free",
    url: "https://www.notion.so/pricing",
    description: "Free for up to 10 guests. Unlimited pages, blocks, and spaces. AI add-on separate.",
    category: "Productivity",
    deal_type: "free_tier",
    deal_detail: "Unlimited pages and blocks. 10 guest collaborators. 5MB file upload limit. 7-day page history.",
    free_until: null,
    value_usd_month: 10,
    score: 85,
    verified: true,
    source: "official",
    tags: ["productivity", "notes", "wiki", "free-tier"],
  },
  {
    name: "Obsidian Free",
    slug: "obsidian-free",
    url: "https://obsidian.md/",
    description: "Free personal use. Markdown knowledge base with backlinks, graphs, and plugins.",
    category: "Productivity",
    deal_type: "free_tier",
    deal_detail: "Free for personal use. Sync and Publish are paid add-ons. Local-first, markdown-based.",
    free_until: null,
    value_usd_month: 4,
    score: 90,
    verified: true,
    source: "official",
    tags: ["productivity", "notes", "knowledge-base", "free-tier"],
  },
  {
    name: "Logseq Free",
    slug: "logseq-free",
    url: "https://logseq.com/",
    description: "Free open-source knowledge base. Outliner, backlinks, graph view. Local-first.",
    category: "Productivity",
    deal_type: "open_source",
    deal_detail: "100% free, open source. AGPL-3.0. Outliner-based, bidirectional links, graph view. Local-first.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["productivity", "notes", "knowledge-base", "open-source"],
  },
  {
    name: "Tana Free",
    slug: "tana-free",
    url: "https://tana.inc/",
    description: "Free personal use. AI-powered outliner and knowledge management. Supertags, live queries.",
    category: "Productivity",
    deal_type: "free_tier",
    deal_detail: "Free for personal use. Unlimited nodes, AI features, supertags. Beta access.",
    free_until: null,
    value_usd_month: 12,
    score: 80,
    verified: true,
    source: "official",
    tags: ["productivity", "notes", "ai", "free-tier"],
  },

  // === FREE TIERS — COMMUNICATION ===
  {
    name: "Discord Free",
    slug: "discord-free",
    url: "https://discord.com/",
    description: "Free voice, video, and text. Unlimited messages, 100k members/server. Screen sharing.",
    category: "Communication",
    deal_type: "free_tier",
    deal_detail: "Unlimited messages. Voice/video channels. Screen sharing. 100k members per server. 10MB file uploads.",
    free_until: null,
    value_usd_month: 5,
    score: 92,
    verified: true,
    source: "official",
    tags: ["communication", "chat", "voice", "free-tier"],
  },
  {
    name: "Slack Free",
    slug: "slack-free",
    url: "https://slack.com/pricing",
    description: "Free for small teams. 90-day message history, 10 integrations, 1:1 huddles.",
    category: "Communication",
    deal_type: "free_tier",
    deal_detail: "90-day message history. 10 app integrations. 1:1 huddles. 5GB file storage per workspace.",
    free_until: null,
    value_usd_month: 8,
    score: 80,
    verified: true,
    source: "official",
    tags: ["communication", "chat", "team", "free-tier"],
  },
  {
    name: "Microsoft Teams Free",
    slug: "microsoft-teams-free",
    url: "https://www.microsoft.com/en-us/microsoft-teams/free",
    description: "Free for up to 100 participants. 60-minute meetings. 5GB storage per user.",
    category: "Communication",
    deal_type: "free_tier",
    deal_detail: "100 participants per meeting. 60-minute limit. 5GB storage per user. Unlimited chat.",
    free_until: null,
    value_usd_month: 6,
    score: 78,
    verified: true,
    source: "official",
    tags: ["communication", "video", "meeting", "free-tier"],
  },

  // === FREE TIERS — DESIGN ===
  {
    name: "Figma Free",
    slug: "figma-free",
    url: "https://www.figma.com/pricing/",
    description: "Free for 3 Figma files. 3 FigJam boards. Unlimited viewers. Dev Mode limited.",
    category: "Design",
    deal_type: "free_tier",
    deal_detail: "3 Figma files. 3 FigJam boards. Unlimited collaborators (view only). 30-day version history.",
    free_until: null,
    value_usd_month: 15,
    score: 85,
    verified: true,
    source: "official",
    tags: ["design", "ui", "figma", "free-tier"],
  },
  {
    name: "Canva Free",
    slug: "canva-free",
    url: "https://www.canva.com/pricing/",
    description: "Free design tool. 250k+ templates, 5GB storage, AI features included.",
    category: "Design",
    deal_type: "free_tier",
    deal_detail: "250,000+ templates. 5GB cloud storage. Basic AI features. Brand Kit limited.",
    free_until: null,
    value_usd_month: 13,
    score: 88,
    verified: true,
    source: "official",
    tags: ["design", "graphics", "canva", "free-tier", "ai"],
  },
  {
    name: "Penpot Free",
    slug: "penpot-free",
    url: "https://penpot.app/",
    description: "Free open-source design tool. Unlimited projects, collaborators. Self-hostable.",
    category: "Design",
    deal_type: "open_source",
    deal_detail: "100% free, open source. MPL-2.0. Unlimited projects and collaborators. Self-hostable.",
    free_until: null,
    value_usd_month: 0,
    score: 90,
    verified: true,
    source: "github",
    tags: ["design", "ui", "open-source", "figma-alternative"],
  },
  {
    name: "Excalidraw Free",
    slug: "excalidraw-free",
    url: "https://excalidraw.com/",
    description: "Free virtual whiteboard. Hand-drawn style. End-to-end encrypted collaboration.",
    category: "Design",
    deal_type: "free_tier",
    deal_detail: "Free for personal and commercial use. Collaborative. E2E encrypted. Open source.",
    free_until: null,
    value_usd_month: 5,
    score: 88,
    verified: true,
    source: "official",
    tags: ["design", "whiteboard", "collaboration", "free-tier"],
  },

  // === FREE TIERS — AI TOOLS ===
  {
    name: "ChatGPT Free",
    slug: "chatgpt-free",
    url: "https://chat.openai.com/",
    description: "Free access to GPT-4o mini. Limited GPT-4o access. Web browsing, vision, code interpreter.",
    category: "LLM / AI Assistant",
    deal_type: "free_tier",
    deal_detail: "Unlimited GPT-4o mini. Limited GPT-4o. Web browsing. Vision. File upload. Code interpreter. DALL-E limited.",
    free_until: null,
    value_usd_month: 20,
    score: 95,
    verified: true,
    source: "official",
    tags: ["ai", "chatgpt", "openai", "free-tier"],
  },
  {
    name: "Claude Free",
    slug: "claude-free",
    url: "https://claude.ai/",
    description: "Free tier with limited messages. Claude 3.5 Sonnet access. File upload, artifacts.",
    category: "LLM / AI Assistant",
    deal_type: "free_tier",
    deal_detail: "Limited messages per day. Claude 3.5 Sonnet. File upload. Artifacts. Projects. No credit card required.",
    free_until: null,
    value_usd_month: 20,
    score: 90,
    verified: true,
    source: "official",
    tags: ["ai", "claude", "anthropic", "free-tier"],
  },
  {
    name: "Google Gemini Free",
    slug: "gemini-free",
    url: "https://gemini.google.com/",
    description: "Free access to Gemini Advanced with Gemini 1.5 Pro. 1M token context. Google integration.",
    category: "LLM / AI Assistant",
    deal_type: "free_tier",
    deal_detail: "Gemini 1.5 Flash: free, unlimited. Gemini Advanced (1.5 Pro): free 2-month trial. 1M token context. Google Workspace integration.",
    free_until: null,
    value_usd_month: 20,
    score: 92,
    verified: true,
    source: "official",
    tags: ["ai", "gemini", "google", "free-tier"],
  },
  {
    name: "Microsoft Copilot Free",
    slug: "copilot-free",
    url: "https://copilot.microsoft.com/",
    description: "Free access to Copilot with GPT-4 Turbo. Image generation, web search, citations.",
    category: "LLM / AI Assistant",
    deal_type: "free_tier",
    deal_detail: "GPT-4 Turbo access. DALL-E 3 image generation. Web search with citations. No login required for basic use.",
    free_until: null,
    value_usd_month: 20,
    score: 88,
    verified: true,
    source: "official",
    tags: ["ai", "copilot", "microsoft", "free-tier"],
  },
  {
    name: "DeepSeek Free",
    slug: "deepseek-free",
    url: "https://chat.deepseek.com/",
    description: "Free access to DeepSeek V3 and DeepSeek R1. 64K context. Reasoning mode.",
    category: "LLM / AI Assistant",
    deal_type: "free_tier",
    deal_detail: "DeepSeek V3: free, unlimited. DeepSeek R1: free, limited. 64K context. Web search. File upload.",
    free_until: null,
    value_usd_month: 15,
    score: 90,
    verified: true,
    source: "official",
    tags: ["ai", "deepseek", "free-tier", "reasoning"],
  },
  {
    name: "Perplexity Free",
    slug: "perplexity-free",
    url: "https://www.perplexity.ai/",
    description: "Free AI search with citations. 3 Pro searches/day. Unlimited basic searches.",
    category: "AI Search",
    deal_type: "free_tier",
    deal_detail: "Unlimited basic searches. 3 Pro searches/day (GPT-4, Claude). Citations. File upload. Focus modes.",
    free_until: null,
    value_usd_month: 20,
    score: 88,
    verified: true,
    source: "official",
    tags: ["ai", "search", "perplexity", "free-tier"],
  },
  {
    name: "Phind Free",
    slug: "phind-free",
    url: "https://www.phind.com/",
    description: "Free AI search for developers. 300 Pro queries/month. Code-focused answers with citations.",
    category: "Code Assistant",
    deal_type: "free_tier",
    deal_detail: "300 Pro queries/month. Unlimited basic queries. Code-focused. VS Code extension. Custom profiles.",
    free_until: null,
    value_usd_month: 15,
    score: 85,
    verified: true,
    source: "official",
    tags: ["ai", "search", "coding", "free-tier"],
  },

  // === FREE TIERS — INFRASTRUCTURE ===
  {
    name: "Vercel Free",
    slug: "vercel-free",
    url: "https://vercel.com/pricing",
    description: "Free hobby plan. 100GB bandwidth, 100GB-hrs serverless, unlimited static sites.",
    category: "Infrastructure",
    deal_type: "free_tier",
    deal_detail: "100GB bandwidth/month. 100GB-hrs serverless functions. Unlimited static sites. Custom domains. SSL.",
    free_until: null,
    value_usd_month: 20,
    score: 90,
    verified: true,
    source: "official",
    tags: ["hosting", "deploy", "serverless", "free-tier"],
  },
  {
    name: "Netlify Free",
    slug: "netlify-free",
    url: "https://www.netlify.com/pricing/",
    description: "Free tier. 100GB bandwidth, 300 build minutes, 125K serverless invocations.",
    category: "Infrastructure",
    deal_type: "free_tier",
    deal_detail: "100GB bandwidth/month. 300 build minutes. 125K serverless invocations. 1 concurrent build.",
    free_until: null,
    value_usd_month: 19,
    score: 88,
    verified: true,
    source: "official",
    tags: ["hosting", "deploy", "serverless", "free-tier"],
  },
  {
    name: "Railway Free",
    slug: "railway-free",
    url: "https://railway.com/pricing",
    description: "$5 free credits/month for new accounts. Deploy anything. Usage-based pricing.",
    category: "Infrastructure",
    deal_type: "free_credits",
    deal_detail: "$5 free credits/month. No credit card required. Deploy Docker, Node, Python, Go, databases.",
    free_until: null,
    value_usd_month: 5,
    score: 82,
    verified: true,
    source: "official",
    tags: ["hosting", "deploy", "paas", "free-credits"],
  },
  {
    name: "Fly.io Free",
    slug: "fly-free",
    url: "https://fly.io/pricing",
    description: "Free allowance: 3 shared-cpu-1x VMs, 160GB storage, 180GB outbound.",
    category: "Infrastructure",
    deal_type: "free_tier",
    deal_detail: "3 shared-cpu-1x VMs (256MB). 160GB persistent storage. 180GB outbound transfer. Global edge deployment.",
    free_until: null,
    value_usd_month: 5,
    score: 80,
    verified: true,
    source: "official",
    tags: ["hosting", "deploy", "edge", "free-tier"],
  },
  {
    name: "Cloudflare Pages Free",
    slug: "cloudflare-pages-free",
    url: "https://pages.cloudflare.com/",
    description: "Free hosting. Unlimited bandwidth, builds, and sites. Workers integration.",
    category: "Infrastructure",
    deal_type: "free_tier",
    deal_detail: "Unlimited bandwidth. Unlimited builds. Unlimited sites. 500/month Workers requests (free tier).",
    free_until: null,
    value_usd_month: 20,
    score: 92,
    verified: true,
    source: "official",
    tags: ["hosting", "deploy", "edge", "free-tier"],
  },
  {
    name: "Supabase Free",
    slug: "supabase-free",
    url: "https://supabase.com/pricing",
    description: "Free tier: 500MB database, 1GB storage, 50K MAU auth, 500K edge function invocations.",
    category: "Database",
    deal_type: "free_tier",
    deal_detail: "500MB PostgreSQL database. 1GB file storage. 50K monthly active users. 500K edge function invocations.",
    free_until: null,
    value_usd_month: 25,
    score: 90,
    verified: true,
    source: "official",
    tags: ["database", "backend", "baas", "free-tier"],
  },
  {
    name: "PlanetScale Free",
    slug: "planetscale-free",
    url: "https://planetscale.com/pricing",
    description: "Free Hobby plan. 5GB storage, 1 billion reads, 10 million writes/month.",
    category: "Database",
    deal_type: "free_tier",
    deal_detail: "5GB storage. 1 billion reads/month. 10 million writes/month. 3 databases. Branching workflow.",
    free_until: null,
    value_usd_month: 30,
    score: 85,
    verified: true,
    source: "official",
    tags: ["database", "mysql", "serverless", "free-tier"],
  },
  {
    name: "Neon Free",
    slug: "neon-free",
    url: "https://neon.tech/pricing",
    description: "Free tier: 512MB storage, 24/7 compute (0.25 GB RAM), branching, auto-scaling.",
    category: "Database",
    deal_type: "free_tier",
    deal_detail: "512MB storage. 0.25 GB RAM compute. 24/7 availability. Branching. Auto-scaling to zero.",
    free_until: null,
    value_usd_month: 19,
    score: 88,
    verified: true,
    source: "official",
    tags: ["database", "postgres", "serverless", "free-tier"],
  },

  // === FREE TIERS — ANALYTICS / MONITORING ===
  {
    name: "Plausible Free (Self-Hosted)",
    slug: "plausible-self-hosted",
    url: "https://plausible.io/",
    description: "Free self-hosted analytics. Privacy-friendly, lightweight, no cookie banner needed.",
    category: "Analytics",
    deal_type: "open_source",
    deal_detail: "Free self-hosted. AGPL-3.0. Privacy-first. No cookies. Lightweight script (<1KB). Revenue-independent.",
    free_until: null,
    value_usd_month: 0,
    score: 90,
    verified: true,
    source: "github",
    tags: ["analytics", "privacy", "self-hosted", "open-source"],
  },
  {
    name: "Umami Free",
    slug: "umami-free",
    url: "https://umami.is/",
    description: "Free self-hosted analytics. Privacy-focused. Unlimited tracking. Fast, lightweight.",
    category: "Analytics",
    deal_type: "open_source",
    deal_detail: "Free self-hosted. MIT license. Unlimited websites and events. No cookie banners. Fast loading.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["analytics", "privacy", "self-hosted", "open-source"],
  },
  {
    name: "Grafana Free",
    slug: "grafana-free",
    url: "https://grafana.com/pricing/",
    description: "Free OSS edition. Dashboards, alerts, 100+ data sources. Self-hosted or cloud free tier.",
    category: "Monitoring",
    deal_type: "open_source",
    deal_detail: "Free OSS. Apache 2.0. Dashboards, alerts, 100+ data sources. Cloud free tier: 10K metrics, 50GB logs.",
    free_until: null,
    value_usd_month: 0,
    score: 92,
    verified: true,
    source: "github",
    tags: ["monitoring", "dashboards", "observability", "open-source"],
  },
  {
    name: "Uptime Kuma Free",
    slug: "uptime-kuma-free",
    url: "https://uptime.kuma.pet/",
    description: "Free self-hosted uptime monitor. Beautiful UI. 80+ notification types. Docker support.",
    category: "Monitoring",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. Self-hosted. 80+ notification types. Multi-protocol. Beautiful UI.",
    free_until: null,
    value_usd_month: 0,
    score: 90,
    verified: true,
    source: "github",
    tags: ["monitoring", "uptime", "self-hosted", "open-source"],
  },

  // === FREE TIERS — WORKFLOW AUTOMATION ===
  {
    name: "n8n Free",
    slug: "n8n-free",
    url: "https://n8n.io/pricing",
    description: "Free self-hosted. Unlimited workflows, executions. 400+ integrations. AI agent capabilities.",
    category: "Workflow Automation",
    deal_type: "open_source",
    deal_detail: "Free self-hosted. Sustainable Use License. Unlimited workflows and executions. 400+ integrations.",
    free_until: null,
    value_usd_month: 0,
    score: 92,
    verified: true,
    source: "github",
    tags: ["automation", "workflow", "self-hosted", "open-source"],
  },
  {
    name: "Activepieces Free",
    slug: "activepieces-free",
    url: "https://www.activepieces.com/",
    description: "Free open-source Zapier alternative. 200+ integrations. AI flows. Self-hosted.",
    category: "Workflow Automation",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. 200+ integrations. AI flows. No execution limits. Self-hosted.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["automation", "workflow", "zapier-alternative", "open-source"],
  },
  {
    name: "Automatisch Free",
    slug: "automatisch-free",
    url: "https://automatisch.io/",
    description: "Free open-source Zapier alternative. Self-hosted. No code. 60+ integrations.",
    category: "Workflow Automation",
    deal_type: "open_source",
    deal_detail: "Free, open source. AGPL-3.0. Self-hosted. No code. 60+ integrations. Unlimited workflows.",
    free_until: null,
    value_usd_month: 0,
    score: 82,
    verified: true,
    source: "github",
    tags: ["automation", "workflow", "zapier-alternative", "open-source"],
  },

  // === FREE TIERS — EMAIL / MARKETING ===
  {
    name: "Brevo Free",
    slug: "brevo-free",
    url: "https://www.brevo.com/pricing/",
    description: "Free: 300 emails/day, unlimited contacts, email templates, SMS marketing.",
    category: "Email Marketing",
    deal_type: "free_tier",
    deal_detail: "300 emails/day. Unlimited contacts. Email templates. SMS marketing. WhatsApp campaigns.",
    free_until: null,
    value_usd_month: 25,
    score: 85,
    verified: true,
    source: "official",
    tags: ["email", "marketing", "automation", "free-tier"],
  },
  {
    name: "Mailchimp Free",
    slug: "mailchimp-free",
    url: "https://mailchimp.com/pricing/",
    description: "Free: 500 contacts, 1,000 sends/month, 1 audience, basic templates.",
    category: "Email Marketing",
    deal_type: "free_tier",
    deal_detail: "500 contacts. 1,000 emails/month. 1 audience. Basic templates. Landing page builder.",
    free_until: null,
    value_usd_month: 13,
    score: 75,
    verified: true,
    source: "official",
    tags: ["email", "marketing", "newsletter", "free-tier"],
  },
  {
    name: "Listmonk Free",
    slug: "listmonk-free",
    url: "https://listmonk.org/",
    description: "Free self-hosted newsletter & mailing list manager. High performance. No limits.",
    category: "Email Marketing",
    deal_type: "open_source",
    deal_detail: "Free, open source. AGPL-3.0. Self-hosted. Unlimited subscribers and campaigns. High performance.",
    free_until: null,
    value_usd_month: 0,
    score: 90,
    verified: true,
    source: "github",
    tags: ["email", "newsletter", "self-hosted", "open-source"],
  },

  // === LIMITED TIME PROMOTIONS ===
  {
    name: "Claude Pro — Free Trial",
    slug: "claude-pro-trial",
    url: "https://claude.ai/pricing",
    description: "Claude Pro: 5x more usage than free tier. Extended thinking. Priority access. $20/mo after trial.",
    category: "LLM / AI Assistant",
    deal_type: "limited_promotion",
    deal_detail: "Free trial available. 5x more messages. Extended thinking (Claude 3.5 Sonnet). Priority access during high demand.",
    free_until: null,
    value_usd_month: 20,
    score: 85,
    verified: true,
    source: "official",
    tags: ["ai", "claude", "trial", "limited-time"],
  },
  {
    name: "Gemini Advanced — 2 Months Free",
    slug: "gemini-advanced-free",
    url: "https://one.google.com/about/ai-premium",
    description: "Gemini Advanced free for 2 months. Gemini 1.5 Pro, 1M context, Google Workspace integration.",
    category: "LLM / AI Assistant",
    deal_type: "limited_promotion",
    deal_detail: "2 months free. Gemini 1.5 Pro. 1M token context. Google Workspace integration. 2TB storage. $19.99/mo after.",
    free_until: null,
    value_usd_month: 20,
    score: 90,
    verified: true,
    source: "official",
    tags: ["ai", "gemini", "google", "trial", "limited-time"],
  },
  {
    name: "Cursor Pro — Free Trial",
    slug: "cursor-pro-trial",
    url: "https://www.cursor.com/pricing",
    description: "Cursor Pro: Unlimited slow requests, 500 fast requests/month. $20/mo after trial.",
    category: "Code Editor / AI",
    deal_type: "limited_promotion",
    deal_detail: "Free trial. Unlimited slow premium requests. 500 fast premium requests/month. $20/mo after.",
    free_until: null,
    value_usd_month: 20,
    score: 82,
    verified: true,
    source: "official",
    tags: ["coding", "editor", "cursor", "trial", "limited-time"],
  },
  {
    name: "Vercel Pro — Free Trial",
    slug: "vercel-pro-trial",
    url: "https://vercel.com/pricing",
    description: "Vercel Pro free trial. 1TB bandwidth, preview deployments, analytics. $20/mo after.",
    category: "Infrastructure",
    deal_type: "limited_promotion",
    deal_detail: "Free trial. 1TB bandwidth. Preview deployments. Password protection. Analytics. $20/mo after.",
    free_until: null,
    value_usd_month: 20,
    score: 80,
    verified: true,
    source: "official",
    tags: ["hosting", "deploy", "vercel", "trial", "limited-time"],
  },

  // === OPEN SOURCE TOOLS ===
  {
    name: "Huginn (Self-Hosted)",
    slug: "huginn",
    url: "https://github.com/huginn/huginn",
    description: "Free IFTTT on steroids. Build agents that monitor and act on your behalf. Self-hosted.",
    category: "Automation",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. 14K+ stars. Self-hosted. Build automated agents for any task.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["automation", "self-hosted", "open-source", "agents"],
  },
  {
    name: "BookStack Free",
    slug: "bookstack-free",
    url: "https://www.bookstackapp.com/",
    description: "Free self-hosted wiki & documentation. Simple, opinionated. Laravel-based.",
    category: "Documentation",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. Self-hosted. Simple WYSIWYG editor. Books, chapters, pages.",
    free_until: null,
    value_usd_month: 0,
    score: 85,
    verified: true,
    source: "github",
    tags: ["documentation", "wiki", "self-hosted", "open-source"],
  },
  {
    name: "Cal.com Free",
    slug: "cal-com-free",
    url: "https://cal.com/",
    description: "Free scheduling link. Unlimited bookings, events, team members. Embeddable.",
    category: "Productivity",
    deal_type: "free_tier",
    deal_detail: "Free for individuals. Unlimited bookings. Unlimited event types. Calendar integrations. Embeddable.",
    free_until: null,
    value_usd_month: 12,
    score: 88,
    verified: true,
    source: "official",
    tags: ["scheduling", "calendar", "free-tier"],
  },
  {
    name: "Formbricks Free",
    slug: "formbricks-free",
    url: "https://formbricks.com/",
    description: "Free open-source surveys & forms. In-app surveys, website forms, link surveys.",
    category: "Forms",
    deal_type: "open_source",
    deal_detail: "Free self-hosted. AGPL-3.0. Unlimited surveys, responses, users. In-app, website, link surveys.",
    free_until: null,
    value_usd_month: 0,
    score: 85,
    verified: true,
    source: "github",
    tags: ["surveys", "forms", "open-source", "self-hosted"],
  },
  {
    name: "Metabase Free",
    slug: "metabase-free",
    url: "https://www.metabase.com/",
    description: "Free open-source BI dashboards. 200+ database connectors. No-code query builder.",
    category: "Analytics",
    deal_type: "open_source",
    deal_detail: "Free OSS. AGPL-3.0. 200+ database connectors. No-code query builder. Embeddable dashboards.",
    free_until: null,
    value_usd_month: 0,
    score: 90,
    verified: true,
    source: "github",
    tags: ["analytics", "bi", "dashboards", "open-source"],
  },
  {
    name: "Directus Free",
    slug: "directus-free",
    url: "https://directus.io/",
    description: "Free open-source Headless CMS. REST & GraphQL APIs. No-code admin panel.",
    category: "Developer tools",
    deal_type: "open_source",
    deal_detail: "Free, open source. GPL-3.0. Self-hosted. REST & GraphQL. No-code admin. Custom flows.",
    free_until: null,
    value_usd_month: 0,
    score: 85,
    verified: true,
    source: "github",
    tags: ["cms", "headless", "api", "open-source"],
  },
  {
    name: "PocketBase Free",
    slug: "pocketbase-free",
    url: "https://pocketbase.io/",
    description: "Free open-source backend in 1 file. SQLite, auth, realtime, REST API. Single binary.",
    category: "Database",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. Single Go binary. SQLite. Auth. Realtime subscriptions. Admin UI.",
    free_until: null,
    value_usd_month: 0,
    score: 92,
    verified: true,
    source: "github",
    tags: ["backend", "database", "baas", "open-source"],
  },
  {
    name: "Appwrite Free",
    slug: "appwrite-free",
    url: "https://appwrite.io/pricing",
    description: "Free tier: 75K monthly executions, 10GB storage, 10GB bandwidth, 2 projects.",
    category: "Database",
    deal_type: "free_tier",
    deal_detail: "75K executions/month. 10GB storage. 10GB bandwidth. 2 projects. Auth, database, functions.",
    free_until: null,
    value_usd_month: 15,
    score: 82,
    verified: true,
    source: "official",
    tags: ["backend", "baas", "firebase-alternative", "free-tier"],
  },
  {
    name: "Hasura Free",
    slug: "hasura-free",
    url: "https://hasura.io/pricing/",
    description: "Free tier: 1GB/month data pass-through, 1M API calls, unlimited schema.",
    category: "Database",
    deal_type: "free_tier",
    deal_detail: "1GB/month data pass-through. 1M API calls/month. PostgreSQL/MySQL/MongoDB. GraphQL & REST.",
    free_until: null,
    value_usd_month: 10,
    score: 80,
    verified: true,
    source: "official",
    tags: ["graphql", "api", "database", "free-tier"],
  },
  {
    name: "Deno Deploy Free",
    slug: "deno-deploy-free",
    url: "https://deno.com/deploy",
    description: "Free: 100K requests/day, 512MB memory, 100GB bandwidth. Edge runtime.",
    category: "Infrastructure",
    deal_type: "free_tier",
    deal_detail: "100K requests/day. 512MB memory per request. 100GB bandwidth/month. Global edge deployment.",
    free_until: null,
    value_usd_month: 10,
    score: 82,
    verified: true,
    source: "official",
    tags: ["hosting", "edge", "serverless", "free-tier"],
  },
  {
    name: "Render Free",
    slug: "render-free",
    url: "https://render.com/pricing",
    description: "Free tier: 750 hours/month, 512MB RAM, shared CPU. Auto-deploy from Git.",
    category: "Infrastructure",
    deal_type: "free_tier",
    deal_detail: "750 hours/month. 512MB RAM. Shared CPU. Auto-deploy from Git. Custom domains. SSL.",
    free_until: null,
    value_usd_month: 7,
    score: 78,
    verified: true,
    source: "official",
    tags: ["hosting", "deploy", "paas", "free-tier"],
  },
  {
    name: "Clerk Free",
    slug: "clerk-free",
    url: "https://clerk.com/pricing",
    description: "Free: 10K monthly active users, unlimited sign-ins, MFA, organizations.",
    category: "Security / Auth",
    deal_type: "free_tier",
    deal_detail: "10K monthly active users. Unlimited sign-ins. MFA. Organizations. User management dashboard.",
    free_until: null,
    value_usd_month: 25,
    score: 88,
    verified: true,
    source: "official",
    tags: ["auth", "identity", "user-management", "free-tier"],
  },
  {
    name: "Auth0 Free",
    slug: "auth0-free",
    url: "https://auth0.com/pricing",
    description: "Free: 7,500 active users, unlimited logins, social connections, MFA.",
    category: "Security / Auth",
    deal_type: "free_tier",
    deal_detail: "7,500 monthly active users. Unlimited logins. Social connections. MFA. Universal Login.",
    free_until: null,
    value_usd_month: 23,
    score: 85,
    verified: true,
    source: "official",
    tags: ["auth", "identity", "sso", "free-tier"],
  },
  {
    name: "Lucia Auth Free",
    slug: "lucia-auth-free",
    url: "https://lucia-auth.com/",
    description: "Free open-source auth. Session-based. Framework agnostic. No third-party dependencies.",
    category: "Security / Auth",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. Session-based auth. Framework agnostic. No vendor lock-in.",
    free_until: null,
    value_usd_month: 0,
    score: 82,
    verified: true,
    source: "github",
    tags: ["auth", "open-source", "session", "framework-agnostic"],
  },
  {
    name: "Umami Cloud Free",
    slug: "umami-cloud-free",
    url: "https://umami.is/pricing",
    description: "Free cloud tier: 3 websites, 10K events/month. Self-hosted is unlimited.",
    category: "Analytics",
    deal_type: "free_tier",
    deal_detail: "3 websites. 10K events/month. 1 year data retention. Self-hosted version is unlimited.",
    free_until: null,
    value_usd_month: 9,
    score: 80,
    verified: true,
    source: "official",
    tags: ["analytics", "privacy", "free-tier"],
  },
  {
    name: "HubSpot Free CRM",
    slug: "hubspot-free-crm",
    url: "https://www.hubspot.com/products/crm",
    description: "Free CRM. Unlimited users, 1M contacts, email tracking, forms, live chat.",
    category: "CRM",
    deal_type: "free_tier",
    deal_detail: "Unlimited users. 1M contacts. Email tracking. Forms. Live chat. Meeting scheduler. Reporting.",
    free_until: null,
    value_usd_month: 45,
    score: 90,
    verified: true,
    source: "official",
    tags: ["crm", "sales", "marketing", "free-tier"],
  },
  {
    name: "Twenty CRM Free",
    slug: "twenty-crm-free",
    url: "https://twenty.com/",
    description: "Free open-source CRM. Modern Salesforce alternative. Self-hosted. Customizable.",
    category: "CRM",
    deal_type: "open_source",
    deal_detail: "Free, open source. AGPL-3.0. Self-hosted. Modern UI. Custom objects. API-first.",
    free_until: null,
    value_usd_month: 0,
    score: 85,
    verified: true,
    source: "github",
    tags: ["crm", "sales", "open-source", "salesforce-alternative"],
  },
  {
    name: "Iceberg Free (E-Signatures)",
    slug: "documenso-free",
    url: "https://documenso.com/",
    description: "Free open-source e-signatures. Unlimited documents. Self-hostable. DocuSign alternative.",
    category: "E-Signatures",
    deal_type: "open_source",
    deal_detail: "Free, open source. AGPL-3.0. Unlimited documents. Self-hosted option. Webhooks. API.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["e-signatures", "documents", "open-source", "docusign-alternative"],
  },
  {
    name: "Stirling PDF Free",
    slug: "stirling-pdf-free",
    url: "https://github.com/Stirling-Tools/Stirling-PDF",
    description: "Free self-hosted PDF tool. Edit, convert, merge, split. 50+ operations. No internet needed.",
    category: "PDF Tools",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. 50+ PDF operations. Self-hosted. No data leaves your server.",
    free_until: null,
    value_usd_month: 0,
    score: 92,
    verified: true,
    source: "github",
    tags: ["pdf", "documents", "self-hosted", "open-source"],
  },
  {
    name: "SearXNG Free",
    slug: "searxng-free",
    url: "https://searxng.org/",
    description: "Free self-hosted metasearch engine. 70+ search engines. No tracking. Privacy-first.",
    category: "AI Search",
    deal_type: "open_source",
    deal_detail: "Free, open source. AGPL-3.0. Self-hosted. 70+ search engines. No tracking. Customizable.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["search", "privacy", "self-hosted", "open-source"],
  },
  {
    name: "Ollama Free",
    slug: "ollama-free",
    url: "https://ollama.com/",
    description: "Free local LLM runtime. Run Llama, Mistral, Gemma, Phi locally. One command install.",
    category: "LLM / AI Assistant",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. Run any LLM locally. One command install. API compatible with OpenAI.",
    free_until: null,
    value_usd_month: 0,
    score: 95,
    verified: true,
    source: "github",
    tags: ["llm", "local", "self-hosted", "open-source"],
  },
  {
    name: "LocalAI Free",
    slug: "localai-free",
    url: "https://localai.io/",
    description: "Free self-hosted OpenAI-compatible API. Run LLM, image, audio models locally.",
    category: "LLM / AI Assistant",
    deal_type: "open_source",
    deal_detail: "Free, open source. MIT license. OpenAI-compatible API. LLM, TTS, STT, image gen. CPU/GPU.",
    free_until: null,
    value_usd_month: 0,
    score: 88,
    verified: true,
    source: "github",
    tags: ["llm", "local", "openai-compatible", "open-source"],
  },
  {
    name: "LM Studio Free",
    slug: "lm-studio-free",
    url: "https://lmstudio.ai/",
    description: "Free desktop app. Download and run LLMs locally. Beautiful UI. OpenAI-compatible API.",
    category: "LLM / AI Assistant",
    deal_type: "free_tier",
    deal_detail: "Free for personal and commercial use. Desktop app. Download any model. OpenAI-compatible local server.",
    free_until: null,
    value_usd_month: 0,
    score: 90,
    verified: true,
    source: "official",
    tags: ["llm", "local", "desktop", "free-tier"],
  },
];
